name: Pipeline

on:
  push:
    branches: 
      - "main"
      - "dev"
  pull_request:
    branches: 
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  build:
    runs-on: timo

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Connect to server via SSH and execute start script
      run: |
        sudo apt-get install -y sshpass # Install sshpass for password-based authentication
        echo "${{ secrets.SERVER_PASSWORD }}" | sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "bash -s" < start.sh
      env:
        SSH_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        SSH_USER: ${{ secrets.SERVER_USER }}
        SSH_HOST: ${{ secrets.SERVER_HOST }}
    - name: Test with pytest
      run: |
        pytest
